# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93dbd103257df96823c13a00b4694ba1af1570b3e87b5980f6b49a82def56691b6bb5f12e4dadc5544db8a35ec1da61dbd6190d8fab22e7e4b6340b0693fefe

test:
  secret_key_base: ab2b73ac33d272b62bda099e2fa83e7e49fd5bb0c662379943ba6e914589271c287504e6f9e0b3b59d45b030df08e7d89b111417ef270144c008b3e5baa9eb34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
